/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SellYourHouseRouteImport } from './routes/sell-your-house'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GetACashOfferTodayRouteImport } from './routes/get-a-cash-offer-today'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourHouseRoute = SellYourHouseRouteImport.update({
  id: '/sell-your-house',
  path: '/sell-your-house',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GetACashOfferTodayRoute = GetACashOfferTodayRouteImport.update({
  id: '/get-a-cash-offer-today',
  path: '/get-a-cash-offer-today',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/get-a-cash-offer-today': typeof GetACashOfferTodayRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/sell-your-house': typeof SellYourHouseRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/get-a-cash-offer-today': typeof GetACashOfferTodayRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/sell-your-house': typeof SellYourHouseRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/get-a-cash-offer-today': typeof GetACashOfferTodayRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/sell-your-house': typeof SellYourHouseRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/contact-us'
    | '/faq'
    | '/get-a-cash-offer-today'
    | '/how-it-works'
    | '/privacy'
    | '/sell-your-house'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/contact-us'
    | '/faq'
    | '/get-a-cash-offer-today'
    | '/how-it-works'
    | '/privacy'
    | '/sell-your-house'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/contact-us'
    | '/faq'
    | '/get-a-cash-offer-today'
    | '/how-it-works'
    | '/privacy'
    | '/sell-your-house'
    | '/terms-conditions'
    | '/testimonials'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqRoute: typeof FaqRoute
  GetACashOfferTodayRoute: typeof GetACashOfferTodayRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  SellYourHouseRoute: typeof SellYourHouseRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-house': {
      id: '/sell-your-house'
      path: '/sell-your-house'
      fullPath: '/sell-your-house'
      preLoaderRoute: typeof SellYourHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-cash-offer-today': {
      id: '/get-a-cash-offer-today'
      path: '/get-a-cash-offer-today'
      fullPath: '/get-a-cash-offer-today'
      preLoaderRoute: typeof GetACashOfferTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  ContactUsRoute: ContactUsRoute,
  FaqRoute: FaqRoute,
  GetACashOfferTodayRoute: GetACashOfferTodayRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  SellYourHouseRoute: SellYourHouseRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
